version: '3.8'
services:
  web:
    container_name: react-vite-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
