version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: paquetesdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
